### ISSUE TITLE
Suggestion: JSON Assert

### ISSUE THREAD

**Issue by Joscorbe** [dlanza1/ExDeMon#1]
Discussion: Probably we should use/develop some method to compare JSON Objects in tests, instead of hardcoding the expected result, because same objects could have keys in different order, which would fail the test when they are actually the same object.

**Comment by dlanza1** [comment]
That makes a lot of sense, go for it!

**Comment by dlanza1** [comment]
One of us should take take of it? split? as you wish.

**Comment by Joscorbe** [comment]
I think this library is quite simple and fits our purpose perfectly:
http://jsonassert.skyscreamer.org/quickstart.html
